%noparser%
		SELECT B1_GRUPO AS GRUPO,
		B1_GRPRECO AS GRPRECO,
		B1_PE AS ENTREGA,
		B1_CONV AS CONVERSAO,
		B1_SEGUM AS SEGUM,
		B1_SKRECU AS MOINHO,
		B1_COD AS CODIGO,
		B1_DESC AS DESCRICAO,
		B1_TIPO AS TIPO,
		B1_UM AS UNIDADE,

		B9_QINI AS SALDB9,

		B2_QATU AS SALDB2,
		(B2_QATU-B2_RESERVA) AS DISP_PA,
		(B2_QATU-B2_QEMP) AS DISP_MP,

		SD3_EMB.QTDE AS CONSU_EMB,
		(SD3_3M.D3_QUANT/3) AS MD3EMB,
		(SD3_XM.D3_QUANT/%EXP: nDAT_14%) AS MDXEMB,
		(SD3_6M.D3_QUANT/6) AS MD6EMB,

		SD4_EMPM.D4_QUANT AS EMPENHOM,
		SD4_EMPS.D4_QUANT AS EMPENHOS,

		SD5_502.D5_QUANT AS VUNID,
		(SD5_PA3M.D5_QUANT/3) AS MD3PA,
		(SD5_PAXM.D5_QUANT/%EXP: nDAT_14%) AS MDXPA,
		(SD5_PA6M.D5_QUANT/6) AS MD6PA,

		SD5_999.D5_QUANT	AS CONSUMO,
		(SD5_3M.D5_QUANT/3) AS MD3MP,
		(SD5_XM.D5_QUANT/%EXP: nDAT_14%) AS MDXMP,
		(SD5_6M.D5_QUANT/6) AS MD6MP,

		SD5_10.D5_QUANT AS ATEUND,

		(C2_QUANT-C2_QUJE) AS PREVUND,

		SD1_ENT.QTDE AS ENTRADAS,

		COALESCE (SC7_ATUAL.QTDE + SC1_ATUAL.QTDE,SC7_ATUAL.QTDE,SC1_ATUAL.QTDE) AS PREVATUAL,
		COALESCE (SC7_SEGUIN.QTDE + SC1_SEGUIN.QTDE,SC7_SEGUIN.QTDE,SC1_SEGUIN.QTDE) AS PREVSEGU

		FROM (SELECT B1_COD, B1_DESC,B1_TIPO,B1_UM,B1_CONV,B1_GRUPO,B1_GRPRECO,B1_PE,B1_SKRECU,B1_SEGUM FROM %TABLE:SB1% SB1 (NOLOCK) WHERE SB1.B1_MSBLQL = '2' AND (B1_TIPO NOT IN ('AF','GG','MC','PV','IM','AI','BN','MO') %EXP:cQueryB1%)%EXP:cQueryEX% AND SB1.%notDel% ) AS SB1

		LEFT JOIN (SELECT B9_COD, SUM(B9_QINI) AS B9_QINI FROM %TABLE:SB9% SB9 (NOLOCK) WHERE B9_DATA = %EXP:cQueryB9% AND	SB9.%notDel% GROUP BY B9_COD) AS SB9 ON SB1.B1_COD = SB9.B9_COD

		LEFT JOIN (SELECT B2_COD, SUM(B2_QATU) AS B2_QATU, SUM(B2_RESERVA) AS B2_RESERVA, SUM(B2_QEMP) AS B2_QEMP FROM %TABLE:SB2% SB2 (NOLOCK) WHERE SB2.%notDel% %EXP:cQueryB2% GROUP BY B2_COD) AS SB2 ON SB1.B1_COD = SB2.B2_COD

		LEFT JOIN (SELECT C2_PRODUTO,SUM(C2_QUANT) AS C2_QUANT,SUM(C2_QUJE) AS C2_QUJE FROM %TABLE:SC2% SC2 (NOLOCK) WHERE C2_DATRF = ' ' AND SC2.%notDel% GROUP BY C2_PRODUTO) AS SC2 ON SB1.B1_COD = SC2.C2_PRODUTO

		LEFT JOIN (SELECT D1_COD, SUM(D1_QUANT) AS QTDE FROM %TABLE:SD1% SD1 (NOLOCK) WHERE D1_EMISSAO BETWEEN %EXP:cD_P_ATU% AND %EXP:cQueryD1% AND SD1.%notDel% GROUP BY D1_COD) AS SD1_ENT ON SB1.B1_COD = SD1_ENT.D1_COD

		LEFT JOIN (SELECT D3_COD, SUM(D3_QUANT) AS QTDE FROM %TABLE:SD3% SD3 (NOLOCK) WHERE D3_EMISSAO BETWEEN %EXP:cD_P_ATU% AND %EXP:cQueryD3% AND SD3.%NOTDEL% AND D3_ESTORNO <> 'S' GROUP BY D3_COD) AS SD3_EMB ON SB1.B1_COD	= SD3_EMB.D3_COD
		LEFT JOIN (SELECT D3_COD, SUM(ROUND(D3_QUANT,3)) AS D3_QUANT FROM %TABLE:SD3% SD3 (NOLOCK) WHERE D3_EMISSAO BETWEEN %EXP:cDAT_XM%  AND %EXP:cQ_EX_D3% AND SD3.%notDel% AND D3_ESTORNO <> 'S'  GROUP BY D3_COD) AS SD3_XM  ON SB1.B1_COD = SD3_XM.D3_COD
		LEFT JOIN (SELECT D3_COD, SUM(ROUND(D3_QUANT,3)) AS D3_QUANT FROM %TABLE:SD3% SD3 (NOLOCK) WHERE %EXP:cQ_3M_D3% AND SD3.%notDel% AND D3_ESTORNO <> 'S' GROUP BY D3_COD) AS SD3_3M ON SB1.B1_COD = SD3_3M.D3_COD
		LEFT JOIN (SELECT D3_COD, SUM(ROUND(D3_QUANT,3)) AS D3_QUANT FROM %TABLE:SD3% SD3 (NOLOCK) WHERE D3_EMISSAO BETWEEN %EXP:cDAT_6M%  AND %EXP:cQ_EX_6M% AND SD3.%notDel% AND D3_ESTORNO <> 'S'  GROUP BY D3_COD) AS SD3_6M  ON SB1.B1_COD = SD3_6M.D3_COD

		LEFT JOIN (SELECT D4_COD, SUM(D4_QUANT) AS D4_QUANT FROM %TABLE:SD4% SD4 (NOLOCK) WHERE D4_DATA <= %EXP:cD_U_ATU% AND D4_QUANT <> 0 AND SD4.%notDel% GROUP BY D4_COD) AS SD4_EMPM ON SB1.B1_COD = SD4_EMPM.D4_COD
		LEFT JOIN (SELECT D4_COD, SUM(D4_QUANT) AS D4_QUANT FROM %TABLE:SD4% SD4 (NOLOCK) WHERE D4_DATA  > %EXP:cD_U_ATU% AND D4_QUANT <> 0 AND SD4.%notDel% GROUP BY D4_COD) AS SD4_EMPS ON SB1.B1_COD = SD4_EMPS.D4_COD

		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cD_P_ATU% AND %EXP:cQueryD5% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN = '010' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_10  ON SB1.B1_COD = SD5_10.D5_PRODUTO

		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cD_P_ATU% AND %EXP:cQueryD5% AND SD5.%notDel%AND D5_ESTORNO <> 'S' AND D5_ORIGLAN >= '500' AND D5_ORIGLAN <> '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_502 ON SB1.B1_COD = SD5_502.D5_PRODUTO
		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cDAT_XM%  AND %EXP:cQ_EX_D5% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN >= '500' AND D5_ORIGLAN <> '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_PAXM  ON SB1.B1_COD = SD5_PAXM.D5_PRODUTO
		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE %EXP:cQ_3M_D5% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN >= '500' AND D5_ORIGLAN <> '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_PA3M ON SB1.B1_COD = SD5_PA3M.D5_PRODUTO
		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cDAT_6M%  AND %EXP:cQ_EX_6M% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN >= '500' AND D5_ORIGLAN <> '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_PA6M  ON SB1.B1_COD = SD5_PA6M.D5_PRODUTO

		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cD_P_ATU% AND %EXP:cQueryD5% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN = '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_999 ON SB1.B1_COD = SD5_999.D5_PRODUTO
		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cDAT_XM%  AND %EXP:cQ_EX_D5% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN = '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_XM  ON SB1.B1_COD = SD5_XM.D5_PRODUTO
		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE %EXP:cQ_3M_D5% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN = '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_3M ON SB1.B1_COD = SD5_3M.D5_PRODUTO
		LEFT JOIN (SELECT D5_PRODUTO, SUM(ROUND(D5_QUANT,3)) AS D5_QUANT FROM %TABLE:SD5% SD5 (NOLOCK) WHERE D5_DATA BETWEEN %EXP:cDAT_6M%  AND %EXP:cQ_EX_6M% AND SD5.%notDel% AND D5_ESTORNO <> 'S' AND D5_ORIGLAN = '999' AND D5_DOC <> 'INVENT   ' GROUP BY D5_PRODUTO) AS SD5_6M  ON SB1.B1_COD = SD5_6M.D5_PRODUTO

		LEFT JOIN (SELECT C7_PRODUTO, SUM(C7_QUANT - C7_QUJE) AS QTDE FROM %TABLE:SC7% SC7 (NOLOCK) WHERE C7_DATPRF <= %EXP:cD_U_ATU% AND SC7.%notDel% AND C7_RESIDUO = ' ' GROUP BY C7_PRODUTO) AS SC7_ATUAL ON SB1.B1_COD = SC7_ATUAL.C7_PRODUTO
		LEFT JOIN (SELECT C7_PRODUTO, SUM(C7_QUANT - C7_QUJE) AS QTDE FROM %TABLE:SC7% SC7 (NOLOCK) WHERE C7_DATPRF > %EXP:cD_U_ATU% AND SC7.%notDel% AND C7_RESIDUO = ' ' GROUP BY C7_PRODUTO) AS SC7_SEGUIN ON SB1.B1_COD = SC7_SEGUIN.C7_PRODUTO

		LEFT JOIN (SELECT C1_PRODUTO, SUM(C1_QUANT) AS QTDE FROM %TABLE:SC1% SC1 (NOLOCK) WHERE C1_DATPRF <= %EXP:cD_U_ATU% AND SC1.%NOTDEL% AND C1_PEDIDO = ' ' AND C1_RESIDUO = ' ' GROUP BY C1_PRODUTO) AS SC1_ATUAL ON SB1.B1_COD = SC1_ATUAL.C1_PRODUTO
		LEFT JOIN (SELECT C1_PRODUTO, SUM(C1_QUANT) AS QTDE FROM %TABLE:SC1% SC1 (NOLOCK) WHERE C1_DATPRF > %EXP:cD_U_ATU% AND SC1.%NOTDEL% AND C1_PEDIDO = ' ' AND C1_RESIDUO = ' ' GROUP BY C1_PRODUTO) AS SC1_SEGUIN ON SB1.B1_COD = SC1_SEGUIN.C1_PRODUTO
		ORDER BY CODIGO